spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/20230512_chusho_kigyocho
    url: jdbc:mysql://10.211.55.2:3306/20230512_chusho_kigyocho
    username: root
    password: 6PTXGtQ5jU7B#mbxEUd
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8815
mybatis:
  mapper-locations: classpath:xml/*.xml