spring:
  datasource:
#    url: jdbc:mysql://localhost:12345/20230512_chusho_kigyocho
    url: jdbc:mysql://10.211.55.2:12345/20230512_chusho_kigyocho
    username: root
    password: 6PTXGtQ5jU7B#mbxEUd
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8815
mybatis:
  mapper-locations: classpath:xml/*.xml

pagesize: 20

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致